### ISSUE TITLE
Change default config please

### ISSUE THREAD

**Issue by Glatoo** [react-native-community/react-native-picker#17]
**Can't build release APK because of old build version in build.gradle**
Change:
`android {
    compileSdkVersion 22
    buildToolsVersion 22.0.1

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName 1.0
    }
    lintOptions {
        abortOnError false
    }
}`
To:
`android {
    compileSdkVersion 28
    buildToolsVersion 28.0.3

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName 1.0
    }
    lintOptions {
        abortOnError false
    }
}`

**Comment by jainkuniya** [comment]
hi @Glatoo which ` build.gradle` file are you referring to?

**Comment by chakrihacker** [comment]
Closing this issue, if you are still facing problems feel free to open
