### ISSUE TITLE
这个控件怎么做省市区联动使用 ？

### ISSUE THREAD

**Issue by DYwangxue** [react-native-community/react-native-picker#20]
# Question

这个控件怎么做省市区联动使用 ？我试了这个控件好像不行，有合适的还在维护的控件推荐没

RN 0.60.4版本
-->

**Comment by jainkuniya** [comment]
Hi @DYwangxue thanks for the report. Can you please say bit more about what issue are you facing. And how to reproduce it. 
(also it will be better for me to understand it, if it is in English)

Thanks
