### ISSUE TITLE
Add Typescript types.

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/react-native-picker#3]
Typescript type definitions are currently not exported. An example of where they should be and what this looks like is in the cameraroll repo [here](https://github.com/react-native-community/react-native-picker/blob/5e6cec3e433e710cf80c82ca252bfd04f699514a/.circleci/config.yml#L23-L25).

**Comment by jainkuniya** [comment]
Now this can be closed as https://github.com/react-native-community/react-native-picker/commit/cfb9b2d9c743b5a33edc45f138ed1c9e0c48ce41 is merged
