### ISSUE TITLE
Add new RNCPickerPackage() to the list returned by the getPackages() method

### ISSUE THREAD

**Issue by Andevelop1234** [react-native-community/react-native-picker#33]
Hello,
I`m new in programming and I have a doubt about installing the Picker package.

It says:
Add new RNCPickerPackage() to the list returned by the getPackages() method

But I have not found the getPackages() method inside the file MainActivity.java

This is my code:

`package com.appname;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
import com.reactnativecommunity.picker.RNCPickerPackage;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "appname";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
        return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }
}
`

So where do I paste it? Thanks! :D

**Comment by chakrihacker** [comment]
Thanks for pointing out

**Comment by Naturalclar** [comment]
Fixed with #44
