### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by tmaly1980** [react-native-community/react-native-picker#38]
# Bug

When using this library on iOS, I get a warning:

> ExceptionsManager.js:94 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check your code at PickerAndroid.ios.js:15.
> 
> 

The problem is there never will be a PickerAndroid for iOS. Why is there a PickerAndroid.ios.js file at all? Wouldn't the traditional way be having one Picker.ios.js (for PickerIOS) and Picker.android.js (for PickerAndroid)?

I know the message is pretty much harmless, it just seems to be poor design to ALWAYS have a warning message for normal use of a library.

## Environment info

React native info output:

```
info Fetching system and libraries information...
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 17.90 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.12.3 - ~/.yarn/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 28
      Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-debugger-open: 0.3.11
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.1.5
```

Library version: 1.1.2

## Steps To Reproduce

1. import { Picker } from '@react-native-community/picker'

Describe what you expected to happen:

1. Not receiving this warning message

## Reproducible sample code

`
import { Picker } from '@react-native-community/picker
'`

**Comment by manhthepixta** [comment]
Same issue here. Waiting for the fix

**Comment by Aidurber** [comment]
A PR has been created for this fix, awaiting for review and approval. 

If you use something like [patch-package](https://www.npmjs.com/package/patch-package), this fix is just to return `UnimplementedView` not `<UnimplementedView />` in both `PickerAndroid.ios.js` and `PickerIOS.android.js`

**Comment by chrish-d** [comment]
This seems to be back, using `"react-native": "~0.61.5",` and `"@react-native-community/picker": "^1.3.0",`

**Here's the code:**

```jsx
const [tipValue, setTipValue] = useState(0.2);

...

<Picker
  selectedValue={tipValue}
  onValueChange={(itemValue, itemIndex) => setTipValue(itemValue)}
  style={{ width: "100%", height: 50 }}
>
  <Picker.item label="Fair" value={0.1} />
  <Picker.item label="Reasonable" value={0.2} />
  <Picker.item label="Generous" value={0.35} />
  <Picker.item label="Outrageous" value={0.5} />
  <Picker.item label="Are you nuts?!" value={1} />
</Picker>
```
**Here's the error I'm getting:**

>ExceptionsManager.js:126 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by Manodiestra** [comment]
I have this warning as well.
Using:
"@react-native-community/picker": "^1.6.1",
"react-native": "^0.62.0",
Code:
`
import {Picker} from '@react-native-community/picker';
...
<Picker
  style={this.styles.picker}
  selectedValue={data.LadderModel}
  onValueChange={(itemValue) => {
    this.changeLadderModel(itemValue, data_id);
  }}
>
  <Picker.item label="Model 3" value="3" />
  <Picker.item label="Model 4" value="4" />
  <Picker.item label="Model 5" value="5" />
  <Picker.item label="Other" value="other" />
</Picker>
`
Warning:
ExceptionsManager.js:173 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by ZainaliSyed** [comment]
I also facing this issue with 

"@react-native-picker/picker": "^2.2.0",
"react": "17.0.2",
"react-native": "0.66.1",


**Warning:**
ExceptionsManager.js:173 Warning: React.createElement: type is invalid

```
import {Picker} from '@react-native-community/picker';

<Picker
style={this.styles.picker}
selectedValue={data.LadderModel}
onValueChange={(itemValue) => {
this.changeLadderModel(itemValue, data_id);
}}

<Picker.item label="Model 3" value="3" />
<Picker.item label="Model 4" value="4" />
<Picker.item label="Model 5" value="5" />
<Picker.item label="Other" value="other" />
```
