### ISSUE TITLE
Why so strict? (RN 0.57...0.59)

### ISSUE THREAD

**Issue by kv9991** [react-native-community/react-native-picker#48]
# Question

In `peerDependencies` it requires `react-native` up to 0.59 version. Is there any option to adapt it for 0.60+? I can make a PR but I don't really understand is there any known problems with RN version

**Comment by Naturalclar** [comment]
I agree, the peerDependencies ceiling can be removed, #40 should resolve the issue :)

**Comment by Naturalclar** [comment]
Solved with #40
