### ISSUE TITLE
initializing picker in "dropdown" mode on android triggers onValueChange

### ISSUE THREAD

**Issue by schumannd** [react-native-community/react-native-picker#69]
# Bug

we are trying to attach some additional action to `onValueChange` like focusing a TextInputField. Unfortunately this gets triggered as soon as the page loads. IMO this shouldn't happen.

## Environment info

  Languages:
    Java: 1.8.0_45 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0

  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman

  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 21, 23, 24, 25, 26, 27, 28
      Build Tools: 19.1.0, 21.1.2, 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: a...google_apis | Google APIs Intel x86 Atom Sys..., a... | Intel x86 Atom_64, a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ..., a...google_apis | Google APIs Intel x86 Atom Sys...
      Android NDK: Not Found

## Steps To Reproduce

1. init the Picker e.g. like so:

```
    import { Picker } from '@react-native-community/picker';
    ...
    <Picker selectedValue={this.props.selectedValue} onValueChange={this.androidOnValueChange} mode="dropdown" style={{ width: this.props.widthAndroid }}>
      {this.props.options.map((i) => (
        <Picker.Item label={i.toString()} value={i.toString()} key={i} />
      ))}
    </Picker>
```

2. observe the initial call.

If this is wont-fix, can you maybe provide a workaround? I only came up with ugly timeout based hacks until now.

**Comment by jainkuniya** [comment]
hi @schumannd I tried it on iOS, can not reproduce. For me `onValueChange ` is only triggered when I change the value, not on initial load. If you are still reproducing it, snack link will be a great help.

**Comment by jainkuniya** [comment]
Tested on Android as well, `onValueChange ` is only triggered, when I manually change the picker value.

**Comment by schumannd** [comment]
Try fetching the options and setting them after initializing the picker. Maybe I should have added that.

**Comment by schumannd** [comment]
So maybe the correct bugreport would be:

Can't change the options after initialization without triggering `onValueChange`

**Comment by farwayer** [comment]
I can confirm. Changing picker items triggers `onValueChange` with the first item value even if passed `selectedValue` exists. Look like the problem in native part.
