### ISSUE TITLE
itemStyle property not working in android

### ISSUE THREAD

**Issue by TechAsif** [react-native-community/react-native-picker#75]
**I want to  design individual item in react-native-picker but , the itemStyle property not working:**  
Here is my code:
```
<Picker
                    itemStyle = {{fontWeight:"bold",color:"#ff0000"}}
                    selectedValue={language}
                    mode="dropdown"
                    style={{ height: 50, width: 200 }}
                    onValueChange={(itemValue, itemIndex) => { setLanguage(itemValue) } }>
                    <Picker.Item label="Select Area" value="Select Area" />
                    <Picker.Item label="Dhaka" value="Dhaka" />
                    <Picker.Item label="Chittangong" value="Chittangong" />
                    <Picker.Item label="Khulna" value="Khulna" />
                    <Picker.Item label="Rajshahi" value="Rajshahi" />
                </Picker>
```

**Here is my output:**

![Screenshot_1588846849](https://user-images.githubusercontent.com/41460327/81284754-584ee300-9080-11ea-982d-c4eda9af58a6.png)

**Comment by bfraiman** [comment]
itemStyle its working only in iOS, You can figured out how to style picker here -->https://stackoverflow.com/questions/38921492/how-to-style-the-standard-react-native-android-picker/39141949#39141949

**Comment by TechAsif** [comment]
> itemStyle its working only in iOS, You can figured out how to style picker here -->https://stackoverflow.com/questions/38921492/how-to-style-the-standard-react-native-android-picker/39141949#39141949

Thank You very much

**Comment by bfraiman** [comment]
@TechAsif Please share here your android styles. There are low documentation.

**Comment by TechAsif** [comment]
@bfraiman  sure after completing design i will share my design

**Comment by poojalivin** [comment]
@TechAsif Could you please share the code?

**Comment by poojalivin** [comment]
@TechAsif : Hi. I have implemented the style using your reference. But how to provide margin in front of the text in drop down? I tried adding <item name="android:left">10dp</item> to SpinnerDropDownItem in the example
