### ISSUE TITLE
Warning message about the future of the react-native-picker-select component.

### ISSUE THREAD

**Issue by jochercoles** [react-native-community/react-native-picker#79]
I received the next warning message, I don't know if important for the future, if can give me problems in my application.

Exist any way to do disappear?

**Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker**

Regards, and thank you for your help.

Javier.

**Comment by jainkuniya** [comment]
hi @jochercoles  you will be get this warning, if you are using `Picker` from `react-native`. 

`Picker` will soon get removed from `react-native`. Please migrate it to community one.

**Comment by jochercoles** [comment]
Thank you for your help. But, I sorry for my ignorance, but how I do to migrate to community one, because I use a Select component that sure use a Picker component

Obtener Outlook para Android<https://aka.ms/ghei36>

**Comment by JeremyEllingham** [comment]
@jochercoles if you are using a library or package that then uses Picker inside that library, you will need to raise an issue with the maintainer of that library linking them to this ticket and asking them to update it for you (or you can submit a Pull Request to do it yourself if you know how).

**Comment by jochercoles** [comment]
Thank you @JeremyEllingham. I will see the problem with the team that developed the component.

Regards.

Javier.

**Comment by YDaskaloff** [comment]
> @jochercoles if you are using a library or package that then uses Picker inside that library, you will need to raise an issue with the maintainer of that library linking them to this ticket and asking them to update it for you (or you can submit a Pull Request to do it yourself if you know how).

How do I find out which library exactly uses it? I have two which might be causing the problem, and found no such import in any of them.
